collections:
  pages:
    output: true
    permalink: /:path/
  bitcoinhumour:
    output: true
    permalink: /bitcoin/humour/:path/

markdown: kramdown

permalink: pretty

title: Deryk Makgill's Website
description: Deryk Makgill's Website
image: https://wallpaperaccess.com/full/1556608.jpg
baseurl: /deryk
